export const DEFAULT_LANGUAGE = "en";

export const MIN_MAILBOX_LENGTH = 10;
export const MAX_MAILBOX_LENGTH = 100;
export const MAILBOX_LENGTH = 10;
export const PAGINATE_MAILBOX_CHECK_DELAY_MS = 100;
export const WAIT_FOR_EMAILS_TIMEOUT_MS = 50000;
export const SEND_RECALL_DELAY_MS = 5000;

export const AUTO_SAVE_DRAFT_INTERVAL_MS = 5000;
export const SERVER_CONNECTION_TRY_SLEEP_MS = 2000
export const REALTIME_SEARCH_DELAY_MS = 300;

export const TOGGLE_TEXT_SEPARATOR = "#separator#";
export const ANIMATION_INIT_DELAY_MS = 10;
export const SLIDE_TRANSITION_DURATION_MS = 300;
export const AUTO_CLOSE_TOAST_DELAY_MS = 3000;
